### ISSUE TITLE
ui/locale type not consistent

### ISSUE THREAD

**Issue by vixns** [fulcrologic/fulcro#135]
On initial load, `:ui/locale` is a keyword , `:en`
`(fulcro.client.mutations/change-locale {:lang :es})`  changes it to `"es"`

shouldn't  `lang` be `locale-key` instead  at
https://github.com/fulcrologic/fulcro/blob/e32cc6ba6911cf9c627bbfbeb04ce083a57d7965/src/main/fulcro/client/mutations.cljc#L128

?

**Comment by awkay** [comment]
This needs cleaned up a bit. The key in translation code is a string, but since the state bit is just for reading into an indicator it would be better as a kw. Unfortunately, at this point it has been that way for a while, and changing it will break existing programs.

I'm actually working on an i18n rewrite (which is mostly done), so I'll probably not do any more changes to the existing i18n system. Use strings for your comparisons.
