### ISSUE TITLE
Review new websockets

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#143]
Client fulcro/websockets.cljs
- [x] Test Untested stuff
   - [x] req-params
   - [x] transit-handlers
- [x] Messy code around API response handling
- [x] global-error-callback missing will throw an exception
- [x] Anything you see
- [ ] auto-rety parameters...retry limit?

Server fulcro/websockets.clj
- [x] wrap-api isn't configurable on URI
- [x] Move URI to websockets component and make wrappers use it (no hard-coded /chsk)
- [x] Other sente concerns??? Do we want to handle more events?

Finally, are there any other extension points ppl will want?

**Comment by currentoor** [comment]
https://github.com/fulcrologic/websockets2-demo/pull/1#issuecomment-366158243

I like how on the client you merge custom transit handlers into the tempid ones needed for fulcro. But allowing users to pass in the packer is the most customizable. I see two options

1. Users are allowed to pass in a packer, and fulcro comes with a helper function for creating a packer (otherwise the default packer is used).
```cljs
(defn create-packer [transit-handlers] ...)
```

2. Users pass in transit handlers on both sides, which get merged with the default tempid ones, and the the result is used to construct a packer. Of course sente the sente options map will override these if a packer is included.

Do you have a preference? 2 seems easier for the end user, but 1 seems simpler. I'd rather do 1. Or a different approach?

Also, I'm happy to code this up and update the demo also.

**Comment by awkay** [comment]
Is there an objective technical advantage to packers? Our user base is more
accustomed to transit.

**Comment by currentoor** [comment]
I worked on a project where they had a packer that used edn for small
messages and transit for larger ones. That’s the only technical advantage I
can think of. But that, was probably more of a pre-optimization rather than
proper use case. I doubt it was worth the complexity.

Just transit handlers on both sides is probably good enough. You want me to
do that?

**Comment by awkay** [comment]
Yes, please :)

**Comment by awkay** [comment]
All fixed in 2.3.0. NOTE: API changed slightly.
