### ISSUE TITLE
Optimized re-render

### ISSUE THREAD

**Issue by thheller** [fulcrologic/fulcro#240]
`fulcro` as of `2.6.0` will always re-render from the root. After thinking about this for a while I must say that this is sort of a deal breaker for me.

I would be fine with specifying which idents to re-render in the transaction itself or any other kind of manual optimization that could be done. Yes, I'm optimizing prematurely and I'm not running into performance issues yet but I'm not fine with doing this much unnecessary work for each render (even though that is already optimized pretty well).

I can absolutely understand if this is a non-goal since it won't be an issue for most apps.

As I understand it this used to be possible though? What was the rationale for removing it?

**Comment by wilkerlucio** [comment]
To be honest I think I'm starting to feel issues with root renderings... And I'm starting to get renders that are not fast enough (I can feel the time to render, I did a performance check using prod version, and it takes 750ms to render a modal in my scenario). I understand the original rationale was to remove some complexity out of Fulcro and to avoid some common mistakes people make, that said I think we still need a targeted optimized render for advanced users, otherwise, it can become a deal breaker for some apps. 

But I also need to track better what's going on, see if the root rendering is really the issue, it can be something else (this app in the case is a monster mixing re-frame and Fulcro in ways that I don't recommend anybody to do, and that surely contributes to the problem).

**Comment by wilkerlucio** [comment]
Also, it's worth seeing how all of this will behave when we get async rendering from React. I'll try to do some bumps and use the React Profiler (https://www.netlify.com/blog/2018/08/29/using-the-react-devtools-profiler-to-diagnose-react-app-performance-issues/) to diagnose if my problem is rendering from the root or something else, we surely need more data on this issue.

**Comment by awkay** [comment]
So, please do a flame chart.  The react overhead for a render from root should be relatively light for the React code itself, because most of everything should short-circuit.  The real overhead will be queries. A root *query* can be very expensive.

React is *designed* as a render-from-root system.  The `forceUpdate` call is not recommended (but was used in the prior rendering alg).  The problem with forceUpdate is that is messes with react's notion of prior and next props, which severely complicates lifecycle methods.  In fact, moving from 15 to 16 deprecated a number of lifecycle methods and made it so you cannot use both the old and the new together, but the only way to "fix" the next/prior props is to hack the lifecycle methods.  I can say more, but trust me: you want to use react with render-from-root, and rely on `shouldComponentUpdate`'s optimizations.  Doing it other ways breaks things.  Om Next has had (and still has) lifecycle bugs as a result of trying to hack a "render just this component" into the reconciliation.

@wilkerlucio If you can show that *react* is actually taking you 750ms, then I'm interested...otherwise I'm betting you've got a big query that probably needs to be broken apart with UI routing (union queries).

@thheller the "unnecessary work" is what just about every react program on the planet does, and is the recommended mode of operation.  As Facebook adds things like async rendering, I'm betting that doing anything else will cause additional headaches for those that choose to ignore the documented warnings about using forceUpdate.  The "extra work" is a couple dozen reference compares and a bit of intermediate VDOM generation that is going to prove to be identical.  

If either of you want to try your hand at writing an optimized render that works with `forceUpdate`, I'm happy to take a PR.

I'm also puzzled why you would consider something a deal breaker that you don't actually measure a performance problem from.

**Comment by thheller** [comment]
@awkay it is certainly not what "about every react program" on the planet does and I have been through this optimizing exercise before. So I already measured plenty, albeit outside of `fulcro` but the problem is the same.

I'll try to create a simplistic example that highlights the amount of "unnecessary work" I'm speaking of. You can easily set the Chrome Devtools to use a 6x slowdown to simulate a slower CPU (eg. mobile/tablet). This makes that work much much easier to notice.

The deal-breaker for me is when there is no way to optimize when I need to. I don't have a problem with root render, I just want to be able to skip it when I know nothing else changed.

**Comment by thheller** [comment]
Alright I created a completely simplistic example here:
https://github.com/thheller/fulcro-questions/blob/master/src/main/fq/render_perf.cljs

It is a simple List component which renders a dumb table where you can click each cell to update its value. To simulate a tiny bit more data I just render a secondary List which happens to use the same items. It will not be uncommon for apps to have 25 list items that get displayed twice. Maybe not the same items but the cost will be about the same.

Please correct me if I'm doing something obviously stupid.

I compile this with `shadow-cljs release render-perf` and then used the Chrome Devtools Debugger with a 6x slowdown and clicked 3 random cells. I clicked a few times before and dismissed the first click since it was much slower for some reason.

![fulcro-perf-graph](https://user-images.githubusercontent.com/144930/45122025-ffb89b80-b162-11e8-8582-e7e6b69ea4a2.png)

Discarding the click event itself just the Animation Frame already takes 25ms, which already blows the 60fps goal despite doing barely anything. Yes, 6x slowdown is extreme but my old Android Tablet I use is already slower than that so its not quite as uncommon as one might think.

My point is that if I can't optimize this extremely simple case in a page that has barely any data whatsoever then that is a deal-breaker for me.

**Comment by thheller** [comment]
See https://medium.com/@addyosmani/the-cost-of-javascript-in-2018-7d8950fbb5d4 for a bit of background why I care so much.

I don't care so much about in the case of the `shadow-cljs` UI as I expect people to be on reasonable fast computers when using that but I also build mobile websites that I want to consider using `fulcro` for. I care very much about the performance on slow-ish devices there.

**Comment by awkay** [comment]
So, I can buy your argument.  At the moment I don't have enough info about how React will behave with async rendering to know what to do about it.  I do know that `forceUpdate` is the only way around rendering from root, but that they also document that you should not do that if props or state are changing (which they are in our case).  I can see things going very badly if you're trying to track, for example, prior props, and you've got an async render that can restart, call certain lifecycle methods more than once, and otherwise mess with your ability to track your state. 

The optimization approaches for avoiding rendering that really doesn't need to happen are:

1. Wrap the sections of the screen in a trivial pure component (defsc) with no query (you're just using it as a wrapper to prevent re-evaluation of that section of UI).  The `shouldComponentUpdate` will return false if the props have not changed and prevent the work.
2. Use component local state for things that change rapidly.

In the particular example case you've shown: you're right that non-local refresh could cause significant UI code to run.  I was personally sad to have to remove the `forceUpdate` logic, since I know that it was actually making things like this much faster; however, I had three choices when updating for React 16 and beyond:

1. Ignore the new lifecycle methods altogether (as 2.5.12 basically did).  You're really using React 15 at that point, but at least you can pretend and wait until the bw compat runs out (React 17)
2. Try to preserve the forceUpdate: An invasive refactor that was very difficult to get right and ensure existing apps didn't break.
3. Do what I did (and Facebook recommends): Render from root props.  Use pure components and component local state for advanced UI optimization.

As I said: I'm game for a PR to try to make forceUpdate work. I can even talk you through exactly what the procedure would be based on 2.5.12 code.  The internals are all still available to try to make it work.

I'm not willing to do that until React 17 async ships, because that will possibly come along and break it in crazy ways that are hard to understand.

**Comment by awkay** [comment]
@thheller Would you mind running your perf test against 2.5.12?  I'm curious to see the difference.

**Comment by thheller** [comment]
With only updating the versions and changing no code the performance is about the same. It does shift from `react` to `fulcro` though.

I guess `fulcro` then spends too much time figuring out which idents need to update. Was there a way to specify which idents to render in `2.5.12`? I can only find `:refresh` in relation to `load`.

As far as I understand it you are supposed to use `setState` over `forceUpdate`. I'll see if I can figure out how much work that would take.

**Comment by thheller** [comment]
I re-did the test without `:advanced` since that just obfuscated the flamegraph too much. Instead during in dev it is clearly visible that the time is spent in `forceUpdate`.

![fulcro-force-update](https://user-images.githubusercontent.com/144930/45145067-0e816b80-b1c0-11e8-8ead-fbb62c78140a.png)

`setState` will avoid this since it allows React to delay the update.

https://reactjs.org/docs/react-component.html#setstate

> Think of setState() as a request rather than an immediate command to update the component. For better perceived performance, React may delay it, and then update several components in a single pass. React does not guarantee that the state changes are applied immediately.

**Comment by wilkerlucio** [comment]
@thheller one other way to trigger refresh outside of load is to put the attributes in the transaction, for example: `[(my-mutation {}) :some-key [:item/id "ident"]]`

In the previous example, it would call `my-mutation`, then refresh every component that has `:some-key` on it's query and also the components with ident `[:item/id "ident"]`.

**Comment by awkay** [comment]
So, as Wilker said: you can add follow-on reads to the tx to target data updates to components. You can also add `refresh` section to `defmutation`.  

Here's the thing: In React land they only support props updates when rendered from root. That has always been the model.  Reagent and Om try to buck this by doing forceUpdate on targeted components.  This works to a point, but my opinion so far is that it isn't worth it.  It complicates the code base significantly, hurts forward compatibility, and I'm not sure it actually buys you much real benefit.  Here's why:

1. In reagent, most ppl end up using a single global atom...this means that it degrades pretty quickly to a render from root that relies on `shouldComponentUpdate` for the real optimizations anyhow.
2. In Fulcro 2.5, Om Next: we can actually do index-based/targeted forceUpdate.  By far the biggest CPU win on that, though, is that we don't have to re-run the query of the data model for root props.  The forceUpdate *can* be significant for rare scenarios, but we already have other ways to optimize those...so, complicating the internal rendering (which creates bugs for years) is a bad tradeoff IMO.

The React world, in general, leverages PureComponent and component local state for interactive performance in the UI, and the upcoming async stuff makes it so React can break the root render into bits so that interactivity can stay high in the face of heavy UI updates.  

The PureComponent optimization is the default in Fulcro.  Simply wrapping a section of UI in a `defsc` gets you short-circuit behavior if the props have not changed.  For many UIs this is more than enough to keep a render from root light.

React's mechanism for further UI optimization *is* component local state.

So, the way you're supposed to do forms and things like your performance example above (if you're trying to keep 60fps for a given *hard* interactivity case) is:

1. You do your interactive updates with component local state.
2. You do your real persistence via a debounced `transact!`

So, for example, you might do local updates in component local state with a 200ms debounced call to `transact!`. As long as the users is banging on the mouse (or typing into a form field) it is super-fast, and when they stop clicking/typing they get one 20-50ms frame.  Really not that hard to write, and plenty performant.

**Comment by thheller** [comment]
> ... complicating the internal rendering ... is a bad tradeoff IMO.

The bad tradeoff I'm seeing here is that everything is optimized for Developer Experience but not End-User Experience. Screw their battery or sluggish UIs, as long as it is fast on my machine. Yes, it is better to have a slow but working UI vs a buggy non-working mess but come on ... we can do better than that. :(

I will dig into the `fulcro` internals some more when I have some time, right now I'm supposed to be working on shadow-cljs instead.

**Comment by awkay** [comment]
I say it is a bad tradeoff because it is using the underlying library in a way that was not intended, and is likely to have problems, which is a bad developer *and* end-user experience.  I'm interested in it performing well, but at some point the developer has to take *some* responsibility for optimization.  React gives very clear tools for doing that which are *proven* to be effective. I'm not saying "screw the end-user".  I'm saying that we've already done a lot to make it "as fast as possible under the given constraints".  

Yes, I can come up with microbenchmarks that stress it in ways that could be made better, but IMO we're talking about premature optimization (I have yet to see an example where the measured bad performance would be fixed by forceUpdate), and I think (at the moment at least) *attempting* to offload this additional responsibility *from* the developer *to* the library is currently a bad idea unless we're willing to say "use React 15, or 16 in 15 compatibility mode". Under that constraint the old way is perfectly fine. In which case you can use Fulcro 2.5.12.  I still think you're going to be using component-local state for many of these extreme cases.

**Comment by awkay** [comment]
Oh, and there *is* a known way we could probably double the performance of the fulcro-side of refreshes: integrate `path-meta` into `db->tree`.  Currently we're walking the entire tree of props twice to do that...it is technically still necessary if someone uses a custom read hook, but in 99% of circumstances we could halve that overhead.

The `db->tree` algorithm is also a good target for optimization. Anything we can squeeze out of that will improve overall experience.

If I was putting time in for optimizing: that's where the biggest win is at the moment.

**Comment by thheller** [comment]
So I just took the [workspaces/example](https://github.com/nubank/workspaces/tree/master/examples/workspaces-shadow-example) (updated to 2.6) and turned on "6x throttle". A click on the left nav expand/collapse arrow takes 213ms. There is a suspicious slow `force-children` call in there but regardless this is not ok (in my book).

![workspaces-nav-toggle](https://user-images.githubusercontent.com/144930/45173300-11a04a00-b208-11e8-8594-fe4d59d65dba.png)

I have no clue why it is taking this long but I don't have access to many other fulcro apps I can profile.

Can you please point to me wherever React says that you are supposed to re-render from root? I can't find that anywhere and not a single public React app I can find does that.

**Comment by wilkerlucio** [comment]
If we go in that direction, I would like to bring some suggestions about follow-on reads. From the last time I remember, Fulcro would automatically add some follow-on reads in some scenarios (I know it does in load, not sure where else). 

I would like so suggest that this "smart auto follow-on reads" should be optional, this can give the user a very fine control about what to render (can use idents to target identities or just strait attributes that find components from the reconciler index).

**Comment by awkay** [comment]
That's a good point. I'll add it to the list

**Comment by awkay** [comment]
Closing this for now.  If a PR appears, then fine, otherwise this is available for historical reference as a closed issue.  This doesn't mean I don't think it is worthwhile, just that I don't believe in leaving issues open if there is no definitive plan to work on it.
