### ISSUE TITLE
`use-hooks?` makes computed props to be lost on refresh

### ISSUE THREAD

**Issue by EduardoMRB** [fulcrologic/fulcro#431]
First of all, thanks to all Fulcro contributors, it's being a great experience developing with it so far.

I started using react hooks in some of my components and I noticed a strange behavior when it's used together with computed props and `comp/transact!!`. The computed props are usable on the first render but after a `comp/transact!!` they become `nil`. The problem doesn't happen with `comp/transact!`.

I created a small repo to reproduce the problem: https://github.com/EduardoMRB/computed-props-hooks.

I tried having a look myself at the code but it doesn't seem to be a beginner-friendly issue.

**Comment by awkay** [comment]
Thanks for the repro case. I appreciate it. I'll have a look.

**Comment by awkay** [comment]
Fixed in 3.4.0 on commit 8f9885aff198f58ed1558f1227438510b2c61c25. 3.4.0 isn't released yet, but 3.4.0-SNAPSHOT is on clojars.

FYI: This had nothing to do with hooks, it was a regressing in props tunneling.  I had accidentally dropped the propagation of computed on localized refresh (which is, unfortunately, the *only* thing computed is for 🤦 ).  The `!!` variants do a targeted refresh, whereas the default rendering no longer does targeted refreshes unless asked.  This means that ident-optimized render was also broken. Both should be fixed now.

For reference, here's the workspaces card I created from your repro case to test it out:
https://github.com/fulcrologic/fulcro/blob/develop/src/workspaces/com/fulcrologic/fulcro/issues/issue431_computed_sync_tx_cards.cljs

Notice that you did not need the merge component, since `:initial-state` can initialize a to-many (they empty map impies and automatic call to the child get-initial-state).

**Comment by awkay** [comment]
Oh, also note that 3.4.0 breaks the current Chrome Inspect (intentionally). Only the electron inspect app (websocket based) has been released, so if you move to 3.4.0, you'll have to use that.

**Comment by EduardoMRB** [comment]
Awesome, I'm definitely interested in the fix, thanks for the explanation and including the workspaces link. I hope I can contribute in the future.

> Oh, also note that 3.4.0 breaks the current Chrome Inspect (intentionally). Only the electron inspect app (websocket based) has been released, so if you move to 3.4.0, you'll have to use that.

Noted!
