### ISSUE TITLE
`comp/get-computed` fails in :initLocalState

### ISSUE THREAD

**Issue by helins-io** [fulcrologic/fulcro#455]
Since props are not set on `this` yet, meaning that computed ones are only accessible by manually fetching them in the props given as arg. Not a big deal but a bit counter-intuitive.

**Comment by awkay** [comment]
initLocalState is kinda "special". I do not plan on messing with it. The hot code reload fix had to be backed out because it didn't play well with `this`, and I don't have any personal intention of touching it again. If you want to send a well-tested PR with testing descriptions that show you've thought through and tested all of the possible regressions then you can, but it is a non-priority for my time.

FYI: I close issues that have no planned action. They just make clutter that distracts from real work that will be done.
